#include <cstdint>
#include <iostream>
#include <random>
#include <string>
#include <fstream>
#include <sstream>
#include "Grid.hpp"
#include "Simulation.hpp"
namespace{void help(const char*p){std::cout<<"Usage: "<<p<<" [options]\n\n--config FILE --seed N --sugar N --sugar-per-source N --evaporation X --diffusion X --combat X --max-ants N\n\nInteractive controls:\nSpace pause | R restart | +/- speed | P pheromones | A ants | S sugar | N nests | G graph | I stats | E CSV | LMB add sugar | RMB remove sugar | ESC quit\n";}}
int main(int argc,char**argv){std::uint32_t seed=std::random_device{}();SimulationParameters p;auto loadConfig=[&](const std::string&file){std::ifstream in(file);if(!in){std::cerr<<"Could not open config: "<<file<<"\n";return false;}std::string line;while(std::getline(in,line)){if(line.empty()||line[0]=='#')continue;auto pos=line.find('=');if(pos==std::string::npos)continue;std::string k=line.substr(0,pos),v=line.substr(pos+1);try{if(k=="seed")seed=(std::uint32_t)std::stoul(v);else if(k=="sugar_sources")p.sugarSources=std::stoi(v);else if(k=="sugar_per_source")p.sugarPerSource=std::stoi(v);else if(k=="evaporation")p.pheromoneEvaporation=std::stof(v);else if(k=="diffusion")p.pheromoneDiffusion=std::stof(v);else if(k=="combat")p.combatChance=std::stof(v);else if(k=="max_ants")p.maxAntsPerColony=std::stoi(v);}catch(...){std::cerr<<"Invalid config value: "<<k<<"\n";}}return true;};for(int i=1;i<argc;++i){std::string a=argv[i];auto val=[&](const std::string&name)->std::string{if(a==name&&i+1<argc)return argv[++i];if(a.rfind(name+"=",0)==0)return a.substr(name.size()+1);return{};};try{if(a=="--help"){help(argv[0]);return 0;}if(a=="--config"&&i+1<argc){if(!loadConfig(argv[++i]))return 1;continue;}if(a.rfind("--config=",0)==0){if(!loadConfig(a.substr(9)))return 1;continue;}std::string v;if(!(v=val("--seed")).empty())seed=(std::uint32_t)std::stoul(v);else if(!(v=val("--sugar")).empty())p.sugarSources=std::stoi(v);else if(!(v=val("--sugar-per-source")).empty())p.sugarPerSource=std::stoi(v);else if(!(v=val("--evaporation")).empty())p.pheromoneEvaporation=std::stof(v);else if(!(v=val("--diffusion")).empty())p.pheromoneDiffusion=std::stof(v);else if(!(v=val("--combat")).empty())p.combatChance=std::stof(v);else if(!(v=val("--max-ants")).empty())p.maxAntsPerColony=std::stoi(v);else {std::cerr<<"Unknown argument: "<<a<<"\n";help(argv[0]);return 1;}}catch(...){std::cerr<<"Invalid argument: "<<a<<"\n";return 1;}}Grid grid(seed,p);Simulation sim(grid,seed);sim.run();}
